In [1]:
import pandas as pd

In [7]:
historic = pd.read_csv("RELEVES_ETATS_ASCENSEURS_SNCF_RATP_2021-2024.csv")

/tmp/ipykernel_67241/2341830710.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  historic = pd.read_csv("RELEVES_ETATS_ASCENSEURS_SNCF_RATP_2021-2024.csv")

In [17]:
ratp_escaliers = pd.read_csv("ratp_localisation_escaliers.csv")

In [18]:
ratp_escaliers

,nom,id_escalier,type_esc,nb_marche,rampe,etage,etage.1,transport,compatibilite_pmr,localisation
0,Neuilly-Plaisance,1681522,EM,0.0,OUI,2,2.0,R,Non,POINT (1664329.3825000064 8183834.528700936)
1,Neuilly-Plaisance,1681521,EF,0.0,NON,2,NaN,NaN,NaN,POINT (1664335.1291831804 8183820.698352249)
2,Neuilly-Plaisance,1681517,EF,0.0,OUI,2,NaN,NaN,NaN,POINT (1664329.7091644898 8183830.236635406)
3,Neuilly-Plaisance,1681503,EF,0.0,OUI,2,NaN,NaN,NaN,POINT (1664332.388744174 8183825.695715474)
4,Neuilly-Plaisance,1681523,EF,0.0,OUI,2,NaN,NaN,NaN,POINT (1664342.460116976 8183809.116096983)
...,...,...,...,...,...,...,...,...,...,...
7930,République,100179257,EF,18.0,NON,-1,NaN,NaN,NaN,POINT (1653305.279449177 8185413.0013774475)
7931,République,100179184,EF,20.0,NON,-1,NaN,NaN,NaN,POINT (1653387.3428411044 8185506.632547693)
7932,République,100179253,EF,20.0,OUI,-1,NaN,NaN,NaN,POINT (1653378.98230757 8185502.1184095945)
7933,République,100179179,EF,17.0,NON,-4,NaN,NaN,NaN,POINT (1653266.7856316722 8185482.763964624)
7934,République,100179223,EF,10.0,NON,-4,NaN,NaN,NaN,POINT (1653272.747189228 8185475.841217418)

In [15]:
liste_arret = pd.read_csv("../static/arrets-lignes.csv",  sep=";")

In [16]:
liste_arret

,id,route_long_name,stop_id,stop_name,stop_lon,stop_lat,operatorname,shortname,mode,pointgeo,nom_commune,code_insee
0,IDFM:C01628,415,IDFM:23555,Pyrénées,2.432784,48.604182,TISSE,415,Bus,"48.60418230616452, 2.432783980354898",Lisses,91340
1,IDFM:C01628,415,IDFM:8470,Bel Air,2.435556,48.596181,TISSE,415,Bus,"48.59618055815076, 2.4355558007744027",Lisses,91340
2,IDFM:C01628,415,IDFM:9943,Petits Champs,2.439569,48.592475,TISSE,415,Bus,"48.59247539801418, 2.4395689447050235",Villabé,91659
3,IDFM:C01628,415,IDFM:463431,Mairie,2.452614,48.588596,TISSE,415,Bus,"48.58859608229684, 2.4526139633835498",Villabé,91659
4,IDFM:C01628,415,IDFM:463428,Cimetière,2.455717,48.591417,TISSE,415,Bus,"48.59141690218037, 2.455716885619495",Villabé,91659
...,...,...,...,...,...,...,...,...,...,...,...,...
68905,IDFM:C00813,3443,IDFM:30716,Sivry D605,2.750902,48.529270,Transdev Pays de Fontainebleau,3443,Bus,"48.52927006153598, 2.75090235973137",Sivry-Courtry,77453
68906,IDFM:C00814,3665,IDFM:30389,L'Orme Brisé,2.565462,48.520740,Transdev Melun,3665,Bus,"48.520739541478314, 2.5654620839535363",Pringy,77378
68907,IDFM:C00814,3665,IDFM:31074,Gare de Boissise-le-Roi,2.572488,48.529284,Transdev Melun,3665,Bus,"48.52928410921383, 2.5724883377069334",Boissise-le-Roi,77040
68908,IDFM:C00814,3665,IDFM:30433,Rive de Seine,2.557861,48.529923,Transdev Melun,3665,Bus,"48.529923290206725, 2.5578613989177357",Boissise-le-Roi,77040
68909,IDFM:C00814,3665,IDFM:419913,Valbois,2.570317,48.521765,Transdev Melun,3665,Bus,"48.52176472979261, 2.570316539891062",Boissise-le-Roi,77040

In [84]:
arret_metro = liste_arret[liste_arret["mode"] == "Metro"]

In [99]:
arret = liste_arret[liste_arret["stop_name"]=="Barbara"]

In [101]:
arret

,id,route_long_name,stop_id,stop_name,stop_lon,stop_lat,operatorname,shortname,mode,pointgeo,nom_commune,code_insee
2817,IDFM:C01374,4,IDFM:483277,Barbara,2.317499,48.809790,RATP,4,Metro,"48.80979025430712, 2.3174992240284045",Bagneux,92007
3848,IDFM:C01157,128,IDFM:28760,Barbara,2.316966,48.809967,RATP,128,Bus,"48.809967086467026, 2.3169658400003152",Montrouge,92049
5282,IDFM:C01374,4,IDFM:483313,Barbara,2.317417,48.809799,RATP,4,Metro,"48.8097987811254, 2.3174174096489284",Bagneux,92007
18695,IDFM:C01287,323,IDFM:413267,Barbara,2.318193,48.809821,RATP,323,Bus,"48.8098211964628, 2.3181932930957947",Bagneux,92007
22372,IDFM:C01287,323,IDFM:413268,Barbara,2.318327,48.810038,RATP,323,Bus,"48.810037810903545, 2.3183266331308765",Montrouge,92049
51546,IDFM:C01157,128,IDFM:35148,Barbara,2.316959,48.809463,RATP,128,Bus,"48.80946338671965, 2.3169588198268345",Bagneux,92007

In [102]:
arret = liste_arret[liste_arret["stop_id"]=="IDFM:35148"]

In [103]:
arret

,id,route_long_name,stop_id,stop_name,stop_lon,stop_lat,operatorname,shortname,mode,pointgeo,nom_commune,code_insee
51546,IDFM:C01157,128,IDFM:35148,Barbara,2.316959,48.809463,RATP,128,Bus,"48.80946338671965, 2.3169588198268345",Bagneux,92007

In [54]:
!pip install s3fs

# import des dépendances
import os
import s3fs

# Creation d'un objet filesystem, les variables d'environnement on été automatiquement traitées par Onyxia
S3_ENDPOINT_URL = "https://" + os.environ["AWS_S3_ENDPOINT"]
fs = s3fs.S3FileSystem(client_kwargs={'endpoint_url': S3_ENDPOINT_URL})

# Liste des documents du répertoire partagé dédié au hackathon :
fs.ls("dlb-hackathon/datasets-diffusion", refresh=True)

Requirement already satisfied: s3fs in /opt/conda/lib/python3.12/site-packages (2024.10.0)
Requirement already satisfied: aiobotocore<3.0.0,>=2.5.4 in /opt/conda/lib/python3.12/site-packages (from s3fs) (2.15.1)
Requirement already satisfied: fsspec==2024.10.0.* in /opt/conda/lib/python3.12/site-packages (from s3fs) (2024.10.0)
Requirement already satisfied: aiohttp!=4.0.0a0,!=4.0.0a1 in /opt/conda/lib/python3.12/site-packages (from s3fs) (3.10.10)
Requirement already satisfied: botocore<1.35.24,>=1.35.16 in /opt/conda/lib/python3.12/site-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs) (1.35.23)
Requirement already satisfied: wrapt<2.0.0,>=1.10.10 in /opt/conda/lib/python3.12/site-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs) (1.16.0)
Requirement already satisfied: aioitertools<1.0.0,>=0.5.1 in /opt/conda/lib/python3.12/site-packages (from aiobotocore<3.0.0,>=2.5.4->s3fs) (0.12.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (2.4.3)
Requirement already satisfied: aiosignal>=1.1.2 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (1.3.1)
Requirement already satisfied: attrs>=17.3.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (24.2.0)
Requirement already satisfied: frozenlist>=1.1.1 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (6.1.0)
Requirement already satisfied: yarl<2.0,>=1.12.0 in /opt/conda/lib/python3.12/site-packages (from aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (1.16.0)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in /opt/conda/lib/python3.12/site-packages (from botocore<1.35.24,>=1.35.16->aiobotocore<3.0.0,>=2.5.4->s3fs) (1.0.1)
Requirement already satisfied: python-dateutil<3.0.0,>=2.1 in /opt/conda/lib/python3.12/site-packages (from botocore<1.35.24,>=1.35.16->aiobotocore<3.0.0,>=2.5.4->s3fs) (2.9.0)
Requirement already satisfied: urllib3!=2.2.0,<3,>=1.25.4 in /opt/conda/lib/python3.12/site-packages (from botocore<1.35.24,>=1.35.16->aiobotocore<3.0.0,>=2.5.4->s3fs) (2.2.3)
Requirement already satisfied: idna>=2.0 in /opt/conda/lib/python3.12/site-packages (from yarl<2.0,>=1.12.0->aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (3.10)
Requirement already satisfied: propcache>=0.2.0 in /opt/conda/lib/python3.12/site-packages (from yarl<2.0,>=1.12.0->aiohttp!=4.0.0a0,!=4.0.0a1->s3fs) (0.2.0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil<3.0.0,>=2.1->botocore<1.35.24,>=1.35.16->aiobotocore<3.0.0,>=2.5.4->s3fs) (1.16.0)

['dlb-hackathon/datasets-diffusion/.keep',
 'dlb-hackathon/datasets-diffusion/ascenseurs_historique_etat',
 'dlb-hackathon/datasets-diffusion/courses_transilien_H_J_L_2022_2023',
 'dlb-hackathon/datasets-diffusion/documents_idfm_faq',
 'dlb-hackathon/datasets-diffusion/documents_norme_gtfs',
 'dlb-hackathon/datasets-diffusion/documents_norme_netex',
 'dlb-hackathon/datasets-diffusion/donnees_territoire_GPSEO',
 'dlb-hackathon/datasets-diffusion/equipements_gares_ratp',
 'dlb-hackathon/datasets-diffusion/historique_info_trafic',
 'dlb-hackathon/datasets-diffusion/recherches_itineraires_agregees',
 'dlb-hackathon/datasets-diffusion/reclamations_formulaire_web',
 'dlb-hackathon/datasets-diffusion/twitter',
 'dlb-hackathon/datasets-diffusion/validations_historisees']

In [159]:
def get_list_of_equipements(station_id, line_id, direction):
    liste_arret = pd.read_csv("static/arrets-lignes.csv",  sep=";")

    arret = liste_arret[liste_arret["stop_id"] == station_id]

    # Escaliers
    BUCKET = "dlb-hackathon"
    FILE_KEY_S3 = "equipe-2/ratp_localisation_escaliers.csv"
    FILE_PATH_S3 = BUCKET + "/" + FILE_KEY_S3
    with fs.open(FILE_PATH_S3, mode="rb") as file_in:
        escaliers = pd.read_csv(file_in)

    escaliers_par_arret = escaliers.loc[lambda x: x["nom"]
                                        == arret.stop_name.iloc[0]]

    # Ascenseurs
    BUCKET = "dlb-hackathon"
    FILE_KEY_S3 = "equipe-2/etat-des-ascenseurs.parquet"
    FILE_PATH_S3 = BUCKET + "/" + FILE_KEY_S3

    with fs.open(FILE_PATH_S3, mode="rb") as file_in:
        etat_ascenseurs = pd.read_parquet(file_in)

    ascenseurs_par_arret = etat_ascenseurs.loc[lambda x: x["zdcname"]
                                            == arret.stop_name.iloc[0]]
        
    return escaliers_par_arret[["id_escalier", "nom", "type_esc", "localisation"]], ascenseurs_par_arret[["liftid", "zdcname"]]

In [166]:
def get_list_of_equipements(zdc):

    # Escaliers
    BUCKET = "dlb-hackathon"
    FILE_KEY_S3 = "equipe-2/ratp_localisation_escaliers.csv"
    FILE_PATH_S3 = BUCKET + "/" + FILE_KEY_S3
    with fs.open(FILE_PATH_S3, mode="rb") as file_in:
        escaliers = pd.read_csv(file_in)

    escaliers_par_arret = escaliers.loc[lambda x:(
        x["nom"] == zdc) & (x["type_esc"] == "EM")]

    # Ascenseurs
    BUCKET = "dlb-hackathon"
    FILE_KEY_S3 = "equipe-2/etat-des-ascenseurs.parquet"
    FILE_PATH_S3 = BUCKET + "/" + FILE_KEY_S3

    with fs.open(FILE_PATH_S3, mode="rb") as file_in:
        etat_ascenseurs = pd.read_parquet(file_in)

    ascenseurs_par_arret = etat_ascenseurs.loc[
        lambda x: x["zdcname"] == zdc
    ]

    return (
        escaliers_par_arret[["id_escalier",
                             "type_esc", "localisation"]],
        ascenseurs_par_arret[["liftid", "liftstatus"]],
    )

In [168]:
get_list_of_equipements("Barbara")

(      id_escalier type_esc                                   localisation
 3543      1301664       EM   POINT (1649893.6393588386 8179046.324245046)
 3553      1301635       EM    POINT (1649901.656254023 8178980.715102431)
 3554      1301648       EM   POINT (1649881.4673228825 8179044.839817154)
 3558      1301614       EM   POINT (1649865.4769000083 8179121.289900946)
 3559      1301613       EM   POINT (1649877.5816000113 8179114.244700949)
 3560      1301611       EM   POINT (1649914.1805429254 8178970.231973927)
 3563      1301619       EM   POINT (1649914.1805429254 8178970.231973927)
 3567      1301665       EM    POINT (1649889.4846093298 8178979.22488175)
 3568      1301609       EM   POINT (1649855.5158000106 8179118.449400947)
 3569      1301608       EM    POINT (1649860.785562221 8179116.127129161)
 3570      1301607       EM   POINT (1649864.5718163983 8179118.881769149)
 3571      1301606       EM   POINT (1649864.5166000088 8179120.473300947)
 3572      1301605       EM   POINT (1649875.2050000082 8179116.224750948)
 3573      1301604       EM    POINT (1649883.324431299 8179109.103221683)
 3575      1301602       EM  POINT (1649866.1588052432 8179119.4298904035)
 3576      1301601       EM   POINT (1649864.5007000093 8179121.591100947)
 3577      1301600       EM   POINT (1649875.8878500103 8179114.329350949)
 3578      1301599       EM   POINT (1649883.3499287136 8179102.605193484)
 3579      1301598       EM   POINT (1649912.4715343162 8178970.026373501)
 3580      1301597       EM   POINT (1649860.3441323799 8179120.802757366)
 3581      1301612       EM   POINT (1649883.3499287136 8179102.605193484)
 3582      1301615       EM   POINT (1649866.2124566436 8179118.684972812)
 3589      1301647       EM   POINT (1649893.7111302228 8179045.735557319)
 3590      1301638       EM   POINT (1649881.5392352345 8179044.250758652)
 3591      1301676       EM     POINT (1649889.412643794 8178979.81374465)
 3592      1301668       EM    POINT (1649901.583912303 8178981.303935632),
     liftid liftstatus
 1     1038  available
 2     1039  available
 3     1040  available
 4     1042  available
 577   1041  available
 578   1043  available
 579   1044  available)

In [162]:
ascenseurs_par_arret

,zdcid,zdcxepsg2154,zdcyepsg2154,liftid,liftreason,liftstatus,privateelevatorid,liftsituation,liftdirection,liftstateupdate,liftstate,zdcname,severity,liftmode,centroidzdc
1,70441,649888,6856847,1038,,available,ASC 4 - EQ11-A005-000000301,SA200,Voirie – Mezzanine > toutes directions,2024-11-21T14:11,1,Barbara,1.0,Metro,b'\x01\x01\x00\x00\x00F\x92\xb1\xba\x84\x8a\x0...
2,70441,649888,6856847,1039,,available,ASC 5 - EQ11-A005-000000302,SA200,Voirie – Mezzanine > toutes directions,2024-11-21T14:11,1,Barbara,1.0,Metro,b'\x01\x01\x00\x00\x00F\x92\xb1\xba\x84\x8a\x0...
3,70441,649888,6856847,1040,,available,ASC 1 - EQ11-A005-000000305,CR212,Bagneux – Lucie Aubrac,2024-11-21T14:11,1,Barbara,1.0,Metro,b'\x01\x01\x00\x00\x00F\x92\xb1\xba\x84\x8a\x0...
4,70441,649888,6856847,1042,,available,ASC 7 - EQ11-A005-000000304,SA217,Voirie – Mezzanine > toutes directions,2024-11-21T14:11,1,Barbara,1.0,Metro,b'\x01\x01\x00\x00\x00F\x92\xb1\xba\x84\x8a\x0...
577,70441,649888,6856847,1041,,available,ASC 2 - EQ11-A005-000000306,CR211,Porte de Clignancourt,2024-11-21T14:11,1,Barbara,1.0,Metro,b'\x01\x01\x00\x00\x00F\x92\xb1\xba\x84\x8a\x0...
578,70441,649888,6856847,1043,,available,ASC 6 - EQ11-A005-000000303,SA217,Voirie – Mezzanine > toutes directions,2024-11-21T14:11,1,Barbara,1.0,Metro,b'\x01\x01\x00\x00\x00F\x92\xb1\xba\x84\x8a\x0...
579,70441,649888,6856847,1044,,available,ASC 3 - EQ11-A005-000000300,SA200,Voirie – Mezzanine > toutes directions,2024-11-21T14:11,1,Barbara,1.0,Metro,b'\x01\x01\x00\x00\x00F\x92\xb1\xba\x84\x8a\x0...

In [110]:
liste_arret = pd.read_csv("static/arrets-lignes.csv",  sep=";")

In [140]:
station_id = "IDFM:483277"

In [156]:
liste_arret = pd.read_csv("static/arrets-lignes.csv",  sep=";")

arret = liste_arret[liste_arret["stop_id"] == station_id]

# Escaliers
BUCKET = "dlb-hackathon"
FILE_KEY_S3 = "equipe-2/ratp_localisation_escaliers.csv"
FILE_PATH_S3 = BUCKET + "/" + FILE_KEY_S3
with fs.open(FILE_PATH_S3, mode="rb") as file_in:
    escaliers = pd.read_csv(file_in)

escaliers_par_arret = escaliers.loc[lambda x: x["nom"]
                                    == arret.stop_name.iloc[0]]

# Ascenseurs
BUCKET = "dlb-hackathon"
FILE_KEY_S3 = "equipe-2/etat-des-ascenseurs.parquet"
FILE_PATH_S3 = BUCKET + "/" + FILE_KEY_S3

with fs.open(FILE_PATH_S3, mode="rb") as file_in:
    etat_ascenseurs = pd.read_parquet(file_in)

ascenseurs_par_arret = etat_ascenseurs.loc[lambda x: x["zdcname"]
                                           == arret.stop_name.iloc[0]]

In [161]:
ascenseurs_par_arret

,zdcid,zdcxepsg2154,zdcyepsg2154,liftid,liftreason,liftstatus,privateelevatorid,liftsituation,liftdirection,liftstateupdate,liftstate,zdcname,severity,liftmode,centroidzdc
1,70441,649888,6856847,1038,,available,ASC 4 - EQ11-A005-000000301,SA200,Voirie – Mezzanine > toutes directions,2024-11-21T14:11,1,Barbara,1.0,Metro,b'\x01\x01\x00\x00\x00F\x92\xb1\xba\x84\x8a\x0...
2,70441,649888,6856847,1039,,available,ASC 5 - EQ11-A005-000000302,SA200,Voirie – Mezzanine > toutes directions,2024-11-21T14:11,1,Barbara,1.0,Metro,b'\x01\x01\x00\x00\x00F\x92\xb1\xba\x84\x8a\x0...
3,70441,649888,6856847,1040,,available,ASC 1 - EQ11-A005-000000305,CR212,Bagneux – Lucie Aubrac,2024-11-21T14:11,1,Barbara,1.0,Metro,b'\x01\x01\x00\x00\x00F\x92\xb1\xba\x84\x8a\x0...
4,70441,649888,6856847,1042,,available,ASC 7 - EQ11-A005-000000304,SA217,Voirie – Mezzanine > toutes directions,2024-11-21T14:11,1,Barbara,1.0,Metro,b'\x01\x01\x00\x00\x00F\x92\xb1\xba\x84\x8a\x0...
577,70441,649888,6856847,1041,,available,ASC 2 - EQ11-A005-000000306,CR211,Porte de Clignancourt,2024-11-21T14:11,1,Barbara,1.0,Metro,b'\x01\x01\x00\x00\x00F\x92\xb1\xba\x84\x8a\x0...
578,70441,649888,6856847,1043,,available,ASC 6 - EQ11-A005-000000303,SA217,Voirie – Mezzanine > toutes directions,2024-11-21T14:11,1,Barbara,1.0,Metro,b'\x01\x01\x00\x00\x00F\x92\xb1\xba\x84\x8a\x0...
579,70441,649888,6856847,1044,,available,ASC 3 - EQ11-A005-000000300,SA200,Voirie – Mezzanine > toutes directions,2024-11-21T14:11,1,Barbara,1.0,Metro,b'\x01\x01\x00\x00\x00F\x92\xb1\xba\x84\x8a\x0...

In [160]:
escaliers

,nom,id_escalier,type_esc,nb_marche,rampe,etage,etage.1,transport,compatibilite_pmr,localisation
0,Neuilly-Plaisance,1681522,EM,0.0,OUI,2,2.0,R,Non,POINT (1664329.3825000064 8183834.528700936)
1,Neuilly-Plaisance,1681521,EF,0.0,NON,2,NaN,NaN,NaN,POINT (1664335.1291831804 8183820.698352249)
2,Neuilly-Plaisance,1681517,EF,0.0,OUI,2,NaN,NaN,NaN,POINT (1664329.7091644898 8183830.236635406)
3,Neuilly-Plaisance,1681503,EF,0.0,OUI,2,NaN,NaN,NaN,POINT (1664332.388744174 8183825.695715474)
4,Neuilly-Plaisance,1681523,EF,0.0,OUI,2,NaN,NaN,NaN,POINT (1664342.460116976 8183809.116096983)
...,...,...,...,...,...,...,...,...,...,...
7930,République,100179257,EF,18.0,NON,-1,NaN,NaN,NaN,POINT (1653305.279449177 8185413.0013774475)
7931,République,100179184,EF,20.0,NON,-1,NaN,NaN,NaN,POINT (1653387.3428411044 8185506.632547693)
7932,République,100179253,EF,20.0,OUI,-1,NaN,NaN,NaN,POINT (1653378.98230757 8185502.1184095945)
7933,République,100179179,EF,17.0,NON,-4,NaN,NaN,NaN,POINT (1653266.7856316722 8185482.763964624)
7934,République,100179223,EF,10.0,NON,-4,NaN,NaN,NaN,POINT (1653272.747189228 8185475.841217418)

In [157]:
escaliers_par_arret[["id_escalier", "nom", "type_esc", "localisation"]]

,id_escalier,nom,type_esc,localisation
3543,1301664,Barbara,EM,POINT (1649893.6393588386 8179046.324245046)
3544,1301663,Barbara,EF,POINT (1649861.6556177898 8179120.466407194)
3545,1301674,Barbara,EF,POINT (1649888.6493194231 8179062.576035451)
3546,1301672,Barbara,EF,POINT (1649875.8874390915 8179114.323649959)
3547,1301658,Barbara,EF,POINT (1649893.1315469306 8178965.030146376)
...,...,...,...,...
3603,1301679,Barbara,EF,POINT (1649878.484047318 8179116.111665199)
3604,1301670,Barbara,EF,POINT (1649876.279601604 8179113.218681718)
3605,1301661,Barbara,EF,POINT (1649875.9033812624 8179114.304123716)
3606,1301656,Barbara,EF,POINT (1649878.700618715 8179115.622810087)
3607,1301634,Barbara,EF,POINT (1649875.490956542 8179115.416165509)

In [158]:
ascenseurs_par_arret[["liftid", "zdcname"]]

    liftid  zdcname
1     1038  Barbara
2     1039  Barbara
3     1040  Barbara
4     1042  Barbara
577   1041  Barbara
578   1043  Barbara
579   1044  Barbara

In [142]:
arret.stop_name.iloc[0]

'Barbara'

In [139]:
liste_arret[liste_arret["stop_name"]=="Barbara"]

,id,route_long_name,stop_id,stop_name,stop_lon,stop_lat,operatorname,shortname,mode,pointgeo,nom_commune,code_insee
2817,IDFM:C01374,4,IDFM:483277,Barbara,2.317499,48.809790,RATP,4,Metro,"48.80979025430712, 2.3174992240284045",Bagneux,92007
3848,IDFM:C01157,128,IDFM:28760,Barbara,2.316966,48.809967,RATP,128,Bus,"48.809967086467026, 2.3169658400003152",Montrouge,92049
5282,IDFM:C01374,4,IDFM:483313,Barbara,2.317417,48.809799,RATP,4,Metro,"48.8097987811254, 2.3174174096489284",Bagneux,92007
18695,IDFM:C01287,323,IDFM:413267,Barbara,2.318193,48.809821,RATP,323,Bus,"48.8098211964628, 2.3181932930957947",Bagneux,92007
22372,IDFM:C01287,323,IDFM:413268,Barbara,2.318327,48.810038,RATP,323,Bus,"48.810037810903545, 2.3183266331308765",Montrouge,92049
51546,IDFM:C01157,128,IDFM:35148,Barbara,2.316959,48.809463,RATP,128,Bus,"48.80946338671965, 2.3169588198268345",Bagneux,92007

In [181]:
escaliers

,nom,id_escalier,type_esc,nb_marche,rampe,etage,etage.1,transport,compatibilite_pmr,localisation
0,Neuilly-Plaisance,1681522,EM,0.0,OUI,2,2.0,R,Non,POINT (1664329.3825000064 8183834.528700936)
1,Neuilly-Plaisance,1681521,EF,0.0,NON,2,NaN,NaN,NaN,POINT (1664335.1291831804 8183820.698352249)
2,Neuilly-Plaisance,1681517,EF,0.0,OUI,2,NaN,NaN,NaN,POINT (1664329.7091644898 8183830.236635406)
3,Neuilly-Plaisance,1681503,EF,0.0,OUI,2,NaN,NaN,NaN,POINT (1664332.388744174 8183825.695715474)
4,Neuilly-Plaisance,1681523,EF,0.0,OUI,2,NaN,NaN,NaN,POINT (1664342.460116976 8183809.116096983)
...,...,...,...,...,...,...,...,...,...,...
7930,République,100179257,EF,18.0,NON,-1,NaN,NaN,NaN,POINT (1653305.279449177 8185413.0013774475)
7931,République,100179184,EF,20.0,NON,-1,NaN,NaN,NaN,POINT (1653387.3428411044 8185506.632547693)
7932,République,100179253,EF,20.0,OUI,-1,NaN,NaN,NaN,POINT (1653378.98230757 8185502.1184095945)
7933,République,100179179,EF,17.0,NON,-4,NaN,NaN,NaN,POINT (1653266.7856316722 8185482.763964624)
7934,République,100179223,EF,10.0,NON,-4,NaN,NaN,NaN,POINT (1653272.747189228 8185475.841217418)

In [182]:
etat_ascenseurs

,zdcid,zdcxepsg2154,zdcyepsg2154,liftid,liftreason,liftstatus,privateelevatorid,liftsituation,liftdirection,liftstateupdate,liftstate,zdcname,severity,liftmode,centroidzdc
0,71485,644961,6865544,318,,available,PMR 1 AQ-DEFESP1,Surface - Salle d échange - Quai,La Défense - Grande Arche,2024-11-21T14:11,1,Esplanade de la Défense,1.0,Metro,b'\x01\x01\x00\x00\x00\xf7\x97\x86+\xd2\xfe\x0...
1,70441,649888,6856847,1038,,available,ASC 4 - EQ11-A005-000000301,SA200,Voirie – Mezzanine > toutes directions,2024-11-21T14:11,1,Barbara,1.0,Metro,b'\x01\x01\x00\x00\x00F\x92\xb1\xba\x84\x8a\x0...
2,70441,649888,6856847,1039,,available,ASC 5 - EQ11-A005-000000302,SA200,Voirie – Mezzanine > toutes directions,2024-11-21T14:11,1,Barbara,1.0,Metro,b'\x01\x01\x00\x00\x00F\x92\xb1\xba\x84\x8a\x0...
3,70441,649888,6856847,1040,,available,ASC 1 - EQ11-A005-000000305,CR212,Bagneux – Lucie Aubrac,2024-11-21T14:11,1,Barbara,1.0,Metro,b'\x01\x01\x00\x00\x00F\x92\xb1\xba\x84\x8a\x0...
4,70441,649888,6856847,1042,,available,ASC 7 - EQ11-A005-000000304,SA217,Voirie – Mezzanine > toutes directions,2024-11-21T14:11,1,Barbara,1.0,Metro,b'\x01\x01\x00\x00\x00F\x92\xb1\xba\x84\x8a\x0...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
934,62667,649706,6843023,1156,,available,393645 - ASC.PMR 4577,Quai 2,None,2024-11-21T14:20,1,Gravigny Balizy,1.0,Tramway,b'\x01\x01\x00\x00\x00-Z\t^\xc7\x88\x02@\xde\x...
935,62977,648140,6844987,1152,,available,393611 - ASC.PMR 4566,Quai 2,None,2024-11-21T14:20,1,Longjumeau,1.0,Tramway,b'\x01\x01\x00\x00\x00\xa2\xbd-\xda\xb9\\\x02@...
936,63244,645528,6847403,479,,available,4211,Sortie MASSY VILMORIN,None,2024-11-21T14:22,1,Massy - Palaiseau,1.0,LocalTrain,b'\x01\x01\x00\x00\x00\xbd\xdb\x069h\x13\x02@S...
937,63244,645528,6847403,488,/,unkown,MAPA PMR7-CR237,Voirie (rue Carnot),None,2024-11-18T15:30,0,Massy - Palaiseau,1.0,LocalTrain,b'\x01\x01\x00\x00\x00\xbd\xdb\x069h\x13\x02@S...
938,63880,636493,6855409,539,,available,4073,Passerelle 2 /Voies B-C,La Défense / Dourdan / Etampes / Paris M,2024-11-21T14:22,1,Versailles Chantiers,1.0,LocalTrain,"b'\x01\x01\x00\x00\x00\xa1?b\x88o\x15\x01@&,9T..."

In [127]:
ascenseurs_par_arret

Empty DataFrame
Columns: [zdcid, zdcxepsg2154, zdcyepsg2154, liftid, liftreason, liftstatus, privateelevatorid, liftsituation, liftdirection, liftstateupdate, liftstate, zdcname, severity, liftmode, centroidzdc]
Index: []

In [124]:
liste_arret[liste_arret["mode"]=="Metro"]

,id,route_long_name,stop_id,stop_name,stop_lon,stop_lat,operatorname,shortname,mode,pointgeo,nom_commune,code_insee
2790,IDFM:C01371,1,IDFM:463170,Esplanade de la Défense,2.249931,48.888350,RATP,1,Metro,"48.88834989394862, 2.249931086743073",Courbevoie,92026
2791,IDFM:C01371,1,IDFM:22100,Les Sablons,2.271905,48.881291,RATP,1,Metro,"48.88129083793358, 2.271904762259129",Neuilly-sur-Seine,92051
2792,IDFM:C01371,1,IDFM:463041,Tuileries,2.329678,48.864478,RATP,1,Metro,"48.864477839314645, 2.3296780947116416",Paris,75056
2793,IDFM:C01371,1,IDFM:22091,Hôtel de Ville,2.352068,48.857352,RATP,1,Metro,"48.85735240518587, 2.3520676701391",Paris,75056
2794,IDFM:C01372,2,IDFM:22113,Philippe Auguste,2.390548,48.858175,RATP,2,Metro,"48.858175121260864, 2.3905477055525735",Paris,75056
...,...,...,...,...,...,...,...,...,...,...,...,...
62405,IDFM:C01386,3B,IDFM:21946,Saint-Fargeau,2.404498,48.871843,RATP,3B,Metro,"48.87184337222297, 2.4044981831688688",Paris,75056
62406,IDFM:C01386,3B,IDFM:21947,Porte des Lilas,2.407062,48.876569,RATP,3B,Metro,"48.87656859902798, 2.4070619733807948",Paris,75056
62407,IDFM:C01386,3B,IDFM:462990,Pelleport,2.401497,48.868465,RATP,3B,Metro,"48.86846488701483, 2.4014967922879253",Paris,75056
62408,IDFM:C01387,7B,IDFM:24687,Danube,2.393228,48.881949,RATP,7B,Metro,"48.88194921492064, 2.393228471227492",Paris,75056
62409,IDFM:C01387,7B,IDFM:463132,Bolivar,2.374152,48.880790,RATP,7B,Metro,"48.880789805531926, 2.374152140698752",Paris,75056

In [121]:
arret.stop_name.iloc[0]

'Pyrénées'

In [105]:
etat_ascenseurs.loc[lambda x: x["zdcname"]==arret.stop_name.iloc[0]]

,zdcid,zdcxepsg2154,zdcyepsg2154,liftid,liftreason,liftstatus,privateelevatorid,liftsituation,liftdirection,liftstateupdate,liftstate,zdcname,severity,liftmode,centroidzdc
1,70441,649888,6856847,1038,,available,ASC 4 - EQ11-A005-000000301,SA200,Voirie – Mezzanine > toutes directions,2024-11-21T14:11,1,Barbara,1.0,Metro,b'\x01\x01\x00\x00\x00F\x92\xb1\xba\x84\x8a\x0...
2,70441,649888,6856847,1039,,available,ASC 5 - EQ11-A005-000000302,SA200,Voirie – Mezzanine > toutes directions,2024-11-21T14:11,1,Barbara,1.0,Metro,b'\x01\x01\x00\x00\x00F\x92\xb1\xba\x84\x8a\x0...
3,70441,649888,6856847,1040,,available,ASC 1 - EQ11-A005-000000305,CR212,Bagneux – Lucie Aubrac,2024-11-21T14:11,1,Barbara,1.0,Metro,b'\x01\x01\x00\x00\x00F\x92\xb1\xba\x84\x8a\x0...
4,70441,649888,6856847,1042,,available,ASC 7 - EQ11-A005-000000304,SA217,Voirie – Mezzanine > toutes directions,2024-11-21T14:11,1,Barbara,1.0,Metro,b'\x01\x01\x00\x00\x00F\x92\xb1\xba\x84\x8a\x0...
577,70441,649888,6856847,1041,,available,ASC 2 - EQ11-A005-000000306,CR211,Porte de Clignancourt,2024-11-21T14:11,1,Barbara,1.0,Metro,b'\x01\x01\x00\x00\x00F\x92\xb1\xba\x84\x8a\x0...
578,70441,649888,6856847,1043,,available,ASC 6 - EQ11-A005-000000303,SA217,Voirie – Mezzanine > toutes directions,2024-11-21T14:11,1,Barbara,1.0,Metro,b'\x01\x01\x00\x00\x00F\x92\xb1\xba\x84\x8a\x0...
579,70441,649888,6856847,1044,,available,ASC 3 - EQ11-A005-000000300,SA200,Voirie – Mezzanine > toutes directions,2024-11-21T14:11,1,Barbara,1.0,Metro,b'\x01\x01\x00\x00\x00F\x92\xb1\xba\x84\x8a\x0...

In [96]:
etat_ascenseurs

,zdcid,zdcxepsg2154,zdcyepsg2154,liftid,liftreason,liftstatus,privateelevatorid,liftsituation,liftdirection,liftstateupdate,liftstate,zdcname,severity,liftmode,centroidzdc
0,71485,644961,6865544,318,,available,PMR 1 AQ-DEFESP1,Surface - Salle d échange - Quai,La Défense - Grande Arche,2024-11-21T14:11,1,Esplanade de la Défense,1.0,Metro,b'\x01\x01\x00\x00\x00\xf7\x97\x86+\xd2\xfe\x0...
1,70441,649888,6856847,1038,,available,ASC 4 - EQ11-A005-000000301,SA200,Voirie – Mezzanine > toutes directions,2024-11-21T14:11,1,Barbara,1.0,Metro,b'\x01\x01\x00\x00\x00F\x92\xb1\xba\x84\x8a\x0...
2,70441,649888,6856847,1039,,available,ASC 5 - EQ11-A005-000000302,SA200,Voirie – Mezzanine > toutes directions,2024-11-21T14:11,1,Barbara,1.0,Metro,b'\x01\x01\x00\x00\x00F\x92\xb1\xba\x84\x8a\x0...
3,70441,649888,6856847,1040,,available,ASC 1 - EQ11-A005-000000305,CR212,Bagneux – Lucie Aubrac,2024-11-21T14:11,1,Barbara,1.0,Metro,b'\x01\x01\x00\x00\x00F\x92\xb1\xba\x84\x8a\x0...
4,70441,649888,6856847,1042,,available,ASC 7 - EQ11-A005-000000304,SA217,Voirie – Mezzanine > toutes directions,2024-11-21T14:11,1,Barbara,1.0,Metro,b'\x01\x01\x00\x00\x00F\x92\xb1\xba\x84\x8a\x0...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
934,62667,649706,6843023,1156,,available,393645 - ASC.PMR 4577,Quai 2,None,2024-11-21T14:20,1,Gravigny Balizy,1.0,Tramway,b'\x01\x01\x00\x00\x00-Z\t^\xc7\x88\x02@\xde\x...
935,62977,648140,6844987,1152,,available,393611 - ASC.PMR 4566,Quai 2,None,2024-11-21T14:20,1,Longjumeau,1.0,Tramway,b'\x01\x01\x00\x00\x00\xa2\xbd-\xda\xb9\\\x02@...
936,63244,645528,6847403,479,,available,4211,Sortie MASSY VILMORIN,None,2024-11-21T14:22,1,Massy - Palaiseau,1.0,LocalTrain,b'\x01\x01\x00\x00\x00\xbd\xdb\x069h\x13\x02@S...
937,63244,645528,6847403,488,/,unkown,MAPA PMR7-CR237,Voirie (rue Carnot),None,2024-11-18T15:30,0,Massy - Palaiseau,1.0,LocalTrain,b'\x01\x01\x00\x00\x00\xbd\xdb\x069h\x13\x02@S...
938,63880,636493,6855409,539,,available,4073,Passerelle 2 /Voies B-C,La Défense / Dourdan / Etampes / Paris M,2024-11-21T14:22,1,Versailles Chantiers,1.0,LocalTrain,"b'\x01\x01\x00\x00\x00\xa1?b\x88o\x15\x01@&,9T..."

In [75]:
etat_ascenseurs[etat_ascenseurs["zdcname"]==arret.stop_name.iloc[0]]

Empty DataFrame
Columns: [zdcid, zdcxepsg2154, zdcyepsg2154, liftid, liftreason, liftstatus, privateelevatorid, liftsituation, liftdirection, liftstateupdate, liftstate, zdcname, severity, liftmode, centroidzdc]
Index: []

In [174]:
# Ascenseurs
BUCKET = "dlb-hackathon"
FILE_KEY_S3 = "equipe-2/accessibilite-en-gare.parquet"
FILE_PATH_S3 = BUCKET + "/" + FILE_KEY_S3

with fs.open(FILE_PATH_S3, mode="rb") as file_in:
    accessibilite = pd.read_parquet(file_in)

accessibilite = accessibilite[["stop_name", "accessibility_level_id", "accessibility_level_name"]]

In [176]:
def get_accessibilite(stop_name):
    BUCKET = "dlb-hackathon"
    FILE_KEY_S3 = "equipe-2/accessibilite-en-gare.parquet"
    FILE_PATH_S3 = BUCKET + "/" + FILE_KEY_S3

    with fs.open(FILE_PATH_S3, mode="rb") as file_in:
        accessibilite = pd.read_parquet(file_in)

    return accessibilite[["stop_name", "accessibility_level_id",
                                   "accessibility_level_name"]].loc[lambda x: x["stop_name"] == stop_name]

In [177]:
get_accessibilite("Achères Grand Cormier")

               stop_name  accessibility_level_id      accessibility_level_name
0  Achères Grand Cormier                       1  gare ou arrêt non accessible

In [175]:
accessibilite

,stop_name,accessibility_level_id,accessibility_level_name
0,Achères Grand Cormier,1,gare ou arrêt non accessible
1,Aéroport Charles de Gaulle 2 (Terminal 2),3,train accessible sur réservation préalable aup...
2,Angerville,1,gare ou arrêt non accessible
3,Arcueil - Cachan,4,train accessible sur demande auprès d'un agent...
4,Aulnay-sous-Bois,3,train accessible sur réservation préalable aup...
...,...,...,...
454,Villeparisis - Mitry-le-Neuf,3,train accessible sur réservation préalable aup...
455,Villiers-sur-Marne - Le Plessis-Trévise,3,train accessible sur réservation préalable aup...
456,Viroflay Rive Droite,3,train accessible sur réservation préalable aup...
457,Vulaines-sur-Seine - Samoreau,1,gare ou arrêt non accessible
458,Yerres,3,train accessible sur réservation préalable aup...

In [173]:
accessibilite[["stop_name", "accessibility_level_id", "accessibility_level_name"]]

,stop_name,accessibility_level_id,accessibility_level_name
0,Achères Grand Cormier,1,gare ou arrêt non accessible
1,Aéroport Charles de Gaulle 2 (Terminal 2),3,train accessible sur réservation préalable aup...
2,Angerville,1,gare ou arrêt non accessible
3,Arcueil - Cachan,4,train accessible sur demande auprès d'un agent...
4,Aulnay-sous-Bois,3,train accessible sur réservation préalable aup...
...,...,...,...
454,Villeparisis - Mitry-le-Neuf,3,train accessible sur réservation préalable aup...
455,Villiers-sur-Marne - Le Plessis-Trévise,3,train accessible sur réservation préalable aup...
456,Viroflay Rive Droite,3,train accessible sur réservation préalable aup...
457,Vulaines-sur-Seine - Samoreau,1,gare ou arrêt non accessible
458,Yerres,3,train accessible sur réservation préalable aup...